namespace: dxl_manager
serial_ports:
    ttyUSB0:
        port_name: /dev/ttyUSB0
        baud_rate: 1000000
        min_motor_id: 1
        max_motor_id: 7 
        update_rate: 10
#    ttyUSB1:
#        port_name: /dev/ttyUSB1
#        baud_rate: 1000000
#        min_motor_id: 2
#        max_motor_id: 24
#        update_rate: 15
#        diagnostics:
#            error_level_temp: 70
#            warn_level_temp: 65
